### ISSUE TITLE
win10: no flif binary found, please use 'export FLIF=/path/to/flif'

### ISSUE THREAD

**Issue by StephanBusch** [matthiaskrgr/flifcrush#28]
I have managed to install Python 3.5.0 x32 and then installed Pillow using 'pip install Pillow' command.
But running flifcrush.py now, I still get those lines:

E:\# Flachbett-Scans>flifcrush.py -c 1968.png
Error: no flif binary found, please use 'export FLIF=/path/to/flif'
Traceback (most recent call last):
  File "E:\Scans\flifcrush.py", line 1429, in <module>
    flif_path = os.environ['FLIF']
  File "C:\Users\SqueezeChart\AppData\Local\Programs\Python\Python35-32\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'FLIF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\# Flachbett-Scans\flifcrush.py", line 1440, in <module>
    os.exit(1)
AttributeError: module 'os' has no attribute 'exit'

Where should flif.exe be placed? I already copied it to C:\Windows\System32

**Comment by Adreitz** [comment]
Stephan,

I figured this out. It's not about placing the FLIF binary somewhere, but you need to add an environmental variable named "FLIF" that has the full path to the FLIF binary (wherever you have it on your drive).

1. Right click on My Computer (or This PC in Windows 10) and select Properties.
2. Click on Advanced System Settings.
3. Click the Environmental Variables... button.
4. Click New...
5. Type "FLIF" as the variable name (no quotation marks) and the full file path to your FLIF binary as the variable value. Alternately, click Browse File..., navigate to your binary, select it, and click Open. The path should look like C:\Path\to\file\flif.exe.

For me, this lets the script run. However, it still isn't producing proper output. It races through the various parameter values in very little time, reporting an output size of 33b each time and finishes. The actual output file is 0b. I might open a new bug for this.

**Comment by Metamaniac** [comment]
@Adreitz this doesn't seem to work on my end, editing around with the .py might have fixed this particular error but is causing entirely new ones which I'm unable to work around, not sure how I'm supposed to make this work on my machine

**Comment by Adreitz** [comment]
@Masterfireheart If you're editing the script yourself, all bets are off. These steps worked for me with a freshly downloaded .zip of the repository with the most recent version of Python 3 for Windows (3.6.5). I installed Pillow using "pip install Image" rather than the command Stephan gave above because I saw it on a different site -- I don't really know anything about Python. It seemed to install Pillow alongside a few other graphics-related libraries.

If you start with a fresh download of the repository and my instructions still don't work, check to make sure that the variable name is exactly:

FLIF

and the path in the variable value **includes the binary name and extension**, not just the folder structure leading to it.

But, again, this still doesn't make the script work properly, since there is some issue with the way that it executes FLIF that ends up producing empty output. I suspect that FLIF is trying to return an error message but that it's being suppressed by the script.
